#!/bin/sh
set -x
set -e

clear
echo

export PATH=${PATH}:/usr/local/bin/
export CURRENT_DIR=$(dirname "$0")
export DOCKERHOST=${DOCKERHOST}

export COMMON_SCRIPT=$(find /app/shared -name "common.sh")
if [ -f ${COMMON_SCRIPT} ]; then
	source ${COMMON_SCRIPT}
fi

pwd

if [[ -d ./$1 ]]; then
	cd ./$1
else
	cd /app
fi

case "$1" in

  'interactive')
	apk add --update --no-cache --no-progress --virtual interactive-deps ${APK_INTERACTIVE} ${APK_INTERACTIVE_CUSTOM}
  	exec /bin/bash
	;;

  'bash')
	apk add --update --no-cache --no-progress bash
  	exec /bin/bash
	;;

  'symlink')
		rebuild_install_scripts_symlinks
	;;

  'dev')
	DOCKER_SCRIPTS=$(find /app/shared/scripts/docker/shell -name "*.sh")
	for FILE_PATH in ${DOCKER_SCRIPTS}; do
		FILE_DIRNAME=$(dirname ${FILE_PATH})
		FILE_NAME=$(basename ${FILE_PATH})
		FILE_BASENAME=$(echo $FILE_NAME | cut -f 1 -d '.')
		echo "FILE_BASENAME: ${FILE_BASENAME} / FILE_NAME: ${FILE_NAME}"		
	done
	apk add --update --no-cache --no-progress --virtual interactive-deps ${APK_INTERACTIVE} ${APK_INTERACTIVE_CUSTOM}
	apk add --update --no-cache --no-progress --virtual build-deps ${APK_BUILD} ${APK_BUILD_CUSTOM}
  	exec /bin/bash
	;;

  launch_*)
	echo "to do"
	;;

  *)
  	exec /bin/bash $@
	;;

esac