#!/bin/sh
set -x
set -e

clear
echo

CURRENT_DIR=$(dirname "$0")

if [ -f ${CURRENT_DIR}/common.sh ]; then
	. ${CURRENT_DIR}/common.sh
fi

pwd

if [[ -d ./$1 ]]; then
	cd ./$1
else
	cd /app
fi

case "$1" in

  'interactive')
	apk add --update --no-cache --no-progress --virtual interactive-deps ${APK_INTERACTIVE} ${APK_INTERACTIVE_CUSTOM}
  	exec /bin/bash
	;;

  'bash')
	apk add --update --no-cache --no-progress bash
  	exec /bin/bash
	;;

  'dev')
	apk add --update --no-cache --no-progress --virtual interactive-deps ${APK_INTERACTIVE} ${APK_INTERACTIVE_CUSTOM}
	apk add --update --no-cache --no-progress --virtual build-deps ${APK_BUILD} ${APK_BUILD_CUSTOM}
  	exec /bin/bash
	;;

  launch_*)
	echo "to do"
	;;

  *)
  	exec $@
	;;

esac