#!/bin/sh
set -x
set -e

clear
echo

export COMMON_SCRIPT=$(find /app/shared -name "common.sh")
if [ -f ${COMMON_SCRIPT} ]; then
	source ${COMMON_SCRIPT}
fi

export COMMON_GOLANG_SCRIPT=$(find /app/shared -name "common-golang.sh")
if [ -f ${COMMON_GOLANG_SCRIPT} ]; then
	source ${COMMON_GOLANG_SCRIPT}
fi




