#!/bin/sh
set -x
set -e

clear
echo

CURRENT_DIR=$(dirname "$0")

if [ -f ${CURRENT_DIR}/common.sh ]; then
	. ${CURRENT_DIR}/common.sh
fi

if [[ -f ./shared/scripts/docker/shell/install-$1.sh ]]; then
	./shared/scripts/docker/shell/install-$1.sh
fi

./shared/scripts/docker/shell/entrypoint.sh
