#!/bin/sh
# set -x
# set -e

clear
echo

echo "import (" > providers.imports.txt
export FILES=$(find `pwd` -name '*.py')
for FILE_PATH in $FILES; do
	FILE_DIRNAME=$(dirname ${FILE_PATH})
	FILE_NAME=$(basename ${FILE_PATH})
	FILE_BASENAME=$(echo $FILE_NAME | cut -f 1 -d '.')
	echo "FILE_BASENAME: ${FILE_BASENAME} / FILE_NAME: ${FILE_NAME}"
	# mkdir -p ./${FILE_BASENAME}
	# mv ${FILE_BASENAME}.py ./${FILE_BASENAME}/
	echo "package ${FILE_BASENAME} \n\n" > ${FILE_BASENAME}/${FILE_BASENAME}.go
	echo "	\""github.com/roscopecoltran/sniperkit-sift/core/providers/${FILE_BASENAME}"\"" >> providers.imports.txt
done

echo ")" >> providers.imports.txt